// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// targetDensity
double targetDensity(double x, const NumericVector& means, const NumericVector& std_devs, const NumericVector& weights);
RcppExport SEXP _SC24002027_targetDensity(SEXP xSEXP, SEXP meansSEXP, SEXP std_devsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type std_devs(std_devsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(targetDensity(x, means, std_devs, weights));
    return rcpp_result_gen;
END_RCPP
}
// mcmcCustomMultiModalSpeckle
NumericMatrix mcmcCustomMultiModalSpeckle(int rows, int cols, NumericVector means, NumericVector std_devs, NumericVector weights, int iterations);
RcppExport SEXP _SC24002027_mcmcCustomMultiModalSpeckle(SEXP rowsSEXP, SEXP colsSEXP, SEXP meansSEXP, SEXP std_devsSEXP, SEXP weightsSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type std_devs(std_devsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcCustomMultiModalSpeckle(rows, cols, means, std_devs, weights, iterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SC24002027_targetDensity", (DL_FUNC) &_SC24002027_targetDensity, 4},
    {"_SC24002027_mcmcCustomMultiModalSpeckle", (DL_FUNC) &_SC24002027_mcmcCustomMultiModalSpeckle, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SC24002027(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
