# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute Target Density for Multimodal Distribution
#' @description This function computes the target density for a given value x, 
#' @param x The value at which to calculate the density.
#' @param means A NumericVector of means for the Gaussian distributions.
#' @param std_devs A NumericVector of standard deviations for the Gaussian distributions.
#' @param weights A NumericVector of weights for the Gaussian distributions.
#' @return The computed target density value.
#' @export
targetDensity <- function(x, means, std_devs, weights) {
    .Call('_SC24002027_targetDensity', PACKAGE = 'SC24002027', x, means, std_devs, weights)
}

#' @title Generate Multimodal Speckle Pattern using MCMC
#' @description This function generates a multimodal speckle pattern using Markov Chain Monte Carlo (MCMC) methods. 
#' @param rows The number of rows in the output matrix.
#' @param cols The number of columns in the output matrix.
#' @param means A NumericVector of means for the Gaussian distributions.
#' @param std_devs A NumericVector of standard deviations for the Gaussian distributions.
#' @param weights A NumericVector of weights for the Gaussian distributions.
#' @param iterations The number of MCMC iterations.
#' @return A NumericMatrix representing the speckle pattern.
#' @examples
#' \dontrun{
#' rows <- 256
#' cols <- 256
#' means <- c(0.3, 0.7)
#' std_devs <- c(0.1, 0.1)
#' weights <- c(0.5, 0.5)
#' iterations <- 500 
#' speckle <- mcmcCustomMultiModalSpeckle(rows, cols, means, std_devs, weights, iterations)
#' image(speckle, col = gray.colors(256), main = "Custom Multi-Modal Speckle")
#' }
#' @export
mcmcCustomMultiModalSpeckle <- function(rows, cols, means, std_devs, weights, iterations) {
    .Call('_SC24002027_mcmcCustomMultiModalSpeckle', PACKAGE = 'SC24002027', rows, cols, means, std_devs, weights, iterations)
}

